server:
  port: 8085

spring:
    datasource:
    datasource:
      url: jdbc:mysql://47.106.115.158:3306/yizu_test?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      table-schema: yizu_test
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    velocity:
        resource-loader-path: classpath:/templates/html
        charset: UTF-8
        suffix: .html
        tool-box-config-location: /WEB-INF/toolbox.xml
mvc:
  view:
    prefix:/WEB-INF/jsp/
    suffix:.jsp


mybatis-plus:
  mapper-locations: classpath:mybatis/*Mapper.xml
  typeAliasesPackage: com.cr.crinporder.core.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    meta-object-handler: com.huzijun.yizunetwork.common.mybatis.MyMetaObjectHandler
    #自定义SQL注入器
#    sql-injector: com.cr.crinporder.common.mybatis.MySqlInjector

logging:
  level:
    root: info
