server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://47.106.115.158:3306/yizu_test?useUnicode=true&characterEncoding=UTF-8
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    table-schema: yizu_test
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    velocity:
      resource-loader-path: classpath:/templates/html
      charset: UTF-8
      suffix: .html
      tool-box-config-location: /WEB-INF/toolbox.xml
    http:
      multipart:
      max-file-size: 2MB
      max-request-size: 10MB
mvc:
  view:
    prefix:/WEB-INF/jsp/
    suffix:.jsp


mybatis-plus:
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  typeAliasesPackage: com.huzijun.yizunetwork.core.*.entity
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    meta-object-handler: com.huzijun.yizunetwork.common.mybatis.MyMetaObjectHandler


logging:
  level:
    root: info
